### ISSUE TITLE
Remove Unnecessary Folders from Projects.

### ISSUE THREAD

**Issue by Funnyguy77** [Apress/basic-math-for-game-dev-w-unity3d#1]
Hi! 

Really enjoying your book so far. It's a good refresher for math concepts that I've been lacking on. 

Anyways, you should look at removing multiple unnecessary folders currently in your repo. These folders contain meta files, cache files, and generally information that Unity creates at runtime. They're not needed to setup the project and actually make it impossible to download as a zip, since the file paths are so long. (See attached image)

The following folders should be removed from each project:
- .vs
- Library
- Debug

Additionally, here is a link to a working (proper) .gitignore file specifically for Unity projects. I suggest using this instead of your current file. [[Link]](https://github.com/github/gitignore/blob/master/Unity.gitignore)

Thanks for your time!

Additional reference to why the Library folder isn't needed can be found here. [[Link]](https://support.unity.com/hc/en-us/articles/205215493-Is-the-Library-Folder-required-in-the-repository-) [[Link 02]](https://answers.unity.com/questions/993291/is-library-folder-necessary.html)

![path-error](https://user-images.githubusercontent.com/12943512/108432154-ed872680-7211-11eb-913a-8fed577dabd7.png)

**Comment by Funnyguy77** [comment]
Side-note: To anyone having trouble downloading the repository from a zip file. It should be noted that you will need to clone the repository to avoid any weird errors relating to file-paths.

**Comment by kelvinhsung** [comment]
Oh boy! How could we have missed this! Thank you so much! The projects are cleaned up with proper gitignore now. Thank you so much for raising this issue. 

Kelvin

**Comment by Funnyguy77** [comment]
@kelvinhsung Happy to help! :)
